// WARNING: Do NOT edit the input and output ports in this file in a text
// editor if you plan to continue editing the block that represents it in
// the Block Editor! File corruption is VERY likely to occur.

// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 350 03/24/2010)
// Created on Fri Mar 06 15:08:35 2020

//  Module Declaration
module UA
(
	// {{ALTERA_ARGS_BEGIN}} DO NOT REMOVE THIS LINE!
	clk, p, Z, clkout, y
	// {{ALTERA_ARGS_END}} DO NOT REMOVE THIS LINE!
);
// Port Declaration

	// {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
	input clk;
	input [8:0] p;
	output Z;
	output clkout;
	output [13:0] y;
	// {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

integer pc=1;
reg [13:0] y;
wire clkout;
reg Z = 0;
assign clkout=!clk;
always @(posedge clk)
begin
case (pc)
1:
	begin	
	y=14'b00000000001101; //0 2 3
	pc = pc + 1;
	end
2:
	begin	
	y=14'b00001001000000; // 6 9
	pc = pc + 1;
	end	
	
3: begin
   y=14'b00000000000100; // 2
   pc = pc + 1;
   end
4:
	begin	
	y=14'b00000000000000;
	if (p[0] == 0) 
		begin
		//y=14'b00000000000000;
		pc = pc + 1;
		end
	else 
		begin
		y=14'b01000000000000; //12
		pc = 20; //конец!
		end
	end
5:
	begin	
	if (p[7] == 0) 
		begin
		y=14'b00000000000000;
		pc = 7;
		end
	else 
		begin
		//y=14'b00000000000000;
		pc = 6; 
		end
	end
	
6: begin
	y=14'b00000000000011; //0 1
	pc = 18; //выдача рез
	end

7:
	begin	
	y=14'b00001100000000; //8 9
	pc = pc + 1;
	end
8:
	begin
	//y=14'b00000000000000;
	if (p[2] == 1) 
		begin
		pc = 17; //перейти к у11
		end
	else 
		begin
		if (p[3] == 1) 
			begin
			pc = 6;
			end
		else pc = pc + 1;
		end
	end
9:
	begin	
	y=14'b00000001100000; //5 6
	pc = pc + 1;
	end
10:
	begin
	//y=14'b00000000000000;
	if (p[1] == 1) 
	begin	
	y=14'b0000001000000; //6
	//pc = pc + 1;
	end
	//else 
	pc = pc + 1;
	end
11:
	begin	
	y=14'b00000000010000; //4
	pc = pc + 1;
	end
12:
	begin
	y=14'b00000000000000;
	if (p[6] == 1) pc = pc + 1; else
		begin
		pc = 9; 
		end
	end
13:
	begin
		if (p[5] == 0) 
			begin
			y=14'b00010000000000; //10
			pc = 14; //на р2
			end
		else 
			begin
			pc = 15; //на р4
			end
	end
14:
	begin
	//y=14'b00000000000000;
	if (p[2] == 0) 
		begin
		y=14'b00000000000000;
		pc = 16; //на р8
		end
	else 
		begin
		pc = 17; //на у11
		end
	end
15:
	begin
	//y=14'b00000000000000;
	if (p[4] == 0) 
	pc =16; //на р8
	else 
	pc = 6;
	end
	
16:
	begin
	//y=14'b00000000000000;
	if (p[8] == 0) 
	begin
	y=14'b00000000000000;
	pc =18; //на выдачу рез
	end
	else
	begin 
	y=14'b10000000000000;//13
	pc = 18;//на выдачу рез
	end
	end	
	
17: begin
	y=14'b00100000000000; //11
	pc = 20; // в конец
	end
		
18: 
	begin
	y=14'b00000010000000;//7
	Z = 1;
	pc=pc+1;
	end


default y=14'b00000000000000;
endcase;
end
endmodule
