// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 350 03/24/2010)
// Created on Tue May 18 11:52:46 2021

UAcourseProject UAcourseProject_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.reset(reset_sig) ,	// input  reset_sig
	.xpin(xpin_sig) ,	// input [9:0] xpin_sig
	.apin(apin_sig) ,	// output [8:0] apin_sig
	.ypin(ypin_sig) ,	// output [11:0] ypin_sig
	.ctpin(ctpin_sig) ,	// output [6:0] ctpin_sig
	.outpin(outpin_sig) 	// output [3:0] outpin_sig
);

