// WARNING: Do NOT edit the input and output ports in this file in a text
// editor if you plan to continue editing the block that represents it in
// the Block Editor! File corruption is VERY likely to occur.

// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 9.1 (Build Build 350 03/24/2010)
// Created on Tue Apr 06 13:22:31 2021

//  Module Declaration




module Z
(
clk, p, clkout, y, Z
);
input clk;

input [7:0] p;

output clkout;

output Z;

output [12:0] y;


integer pc=1; 

reg [12:0] y;

wire clkout; 

reg Z=0; 

assign clkout=!clk; 

always @(posedge clk)

begin

case (pc)
1: begin
y=13'b0100000101010;
pc= pc + 1;
end
2: begin
y=13'b0001001000100;
pc= pc + 1;
end
3: begin
y=13'b0000000001010;
pc= pc + 1;
end
4: begin
if (p[4]==1) begin y=13'b1000001000000; pc=15; end else begin
if (p[5]==1) begin y=15'b0100000000001; pc=15; end else begin
y=13'b0011000000000;
pc= pc + 1;
end;
end
end
5: begin
if (p[3]==1) begin y=13'b1000001000000; pc=15; end else begin
if (p[6]==1) begin y=13'b0100000000001; pc=15; end else begin
if (p[1]==1) begin y=13'b0010000000100; pc=pc+1; end else begin
y=13'b000000000100;
pc= pc + 1;  
end

6: begin
y=13'b0000000010000;
pc=pc+1;
end
7: begin
if (p[0]==0) pc=5 else begin
if (p[6]==0) begin y=13'b0000100000000; pc=pc+1 end else
if (p[2]==1) begin y=13'b0100000000001; pc=15 end3
pc=pc+1;
end
8: begin
if (p[6]==1) begin 
if (p[8]==0) begin
y=15'b000000001000000;
pc=pc+1;
end
else
begin
if (p[4]==1) begin
y=15'b001000000000100;
pc=15;
end
else
begin
pc=15;
end
end
end else
begin
pc=6;
end
end
9:begin
if (p[2]==1) begin 
y=15'b010000000000000;
end
pc= 15;
end

15: begin
Z=1; pc=100; 
end

default y=15'b000000000000000;
endcase;
end
endmodule
	

